import { routeDefinition } from "../policy/contract.js";
import { DevFlowError } from "./errors.js";
import { assertArtifactIntegrity } from "./artifacts.js";
import { mutate, readState, type FeatureState } from "./state-store.js";
import { assertCurrentStep } from "./step-order.js";
import { invalidateStaleVerification } from "./verification.js";
import { deriveRiskRequirements } from "../policy/route.js";
import { assertRequirementsGrillSatisfied } from "./requirements-grill.js";
export async function recordStep(root: string, id: string, expectedRevision: number, step: string, evidence: unknown): Promise<FeatureState> { return mutate(root, id, expectedRevision, "step-recorded", async (state) => { if (state.lifecycle !== "active") throw new DevFlowError("INVALID_LIFECYCLE", "only active features can record steps"); if (["requirement_confirmation", "implementation_approval", "verification", "feature_check", "finalize"].includes(step) || !routeDefinition(state.route).orderedSteps.includes(step)) throw new DevFlowError("INVALID_STEP", step); assertCurrentStep(state, step); await assertRequirementsGrillSatisfied(root, id, state); const reviewType = (evidence as { reviewType?: string })?.reviewType; if ((step === "plan_review" && reviewType !== "plan") || (step === "code_review" && reviewType !== "code")) throw new DevFlowError("REVIEW_TYPE_MISMATCH", step); const risk = deriveRiskRequirements(state.classification.riskLabels); if (step === "risk_controls") { const supplied = (evidence as { checks?: unknown })?.checks; const required = risk.checks.filter((check) => check !== "full-code-review"); if (!Array.isArray(supplied) || required.some((check) => !supplied.includes(check))) throw new DevFlowError("RISK_EVIDENCE_INCOMPLETE", "risk controls do not cover route risk obligations", { required }); } if (step === "code_review" && risk.checks.includes("full-code-review") && (evidence as { reviewDepth?: string })?.reviewDepth !== "full") throw new DevFlowError("RISK_EVIDENCE_INCOMPLETE", "full code review is required"); state.steps[step] = { status: "satisfied", evidence }; }); }
async function invalidateBeforeFinalClaim(root: string, id: string, expectedRevision: number): Promise<void> { const invalidated = await invalidateStaleVerification(root, id, expectedRevision); if (invalidated) throw new DevFlowError("VERIFICATION_STALE", "protected files changed; rerun verification", { currentRevision: invalidated.revision }); }
export async function featureCheck(root: string, id: string, expectedRevision: number): Promise<FeatureState> { const initial = await readState(root, id); if (initial.revision !== expectedRevision) throw new DevFlowError("STATE_REVISION_CONFLICT", "state revision changed", { currentRevision: initial.revision }); await assertRequirementsGrillSatisfied(root, id, initial); await invalidateBeforeFinalClaim(root, id, expectedRevision); await assertArtifactIntegrity(root, id); return mutate(root, id, expectedRevision, "feature-checked", async (state) => { await assertRequirementsGrillSatisfied(root, id, state); assertCurrentStep(state, "feature_check"); if (state.verification.verifiedFingerprint !== state.businessFingerprint) throw new DevFlowError("VERIFICATION_STALE", "protected files changed or verification did not pass"); const evidence = state.steps.verification?.evidence as { kinds?: string[] } | undefined; const requiredKinds = state.classification.riskLabels.length ? deriveRiskRequirements(state.classification.riskLabels).verification : ["targeted"]; if (!Array.isArray(evidence?.kinds) || requiredKinds.some((kind) => !evidence.kinds?.includes(kind))) throw new DevFlowError("RISK_EVIDENCE_INCOMPLETE", "verification did not satisfy risk evidence kinds", { requiredKinds }); state.featureCheck = { passed: true, fingerprint: state.businessFingerprint }; state.steps.feature_check = { status: "satisfied" }; }); }
export async function finalize(root: string, id: string, expectedRevision: number): Promise<FeatureState> { const initial = await readState(root, id); if (initial.revision !== expectedRevision) throw new DevFlowError("STATE_REVISION_CONFLICT", "state revision changed", { currentRevision: initial.revision }); await assertRequirementsGrillSatisfied(root, id, initial); await invalidateBeforeFinalClaim(root, id, expectedRevision); await assertArtifactIntegrity(root, id); return mutate(root, id, expectedRevision, "finalized", async (state) => { await assertRequirementsGrillSatisfied(root, id, state); const route = routeDefinition(state.route); assertCurrentStep(state, "finalize"); if (route.featureCheckRequired && (!state.featureCheck.passed || state.featureCheck.fingerprint !== state.businessFingerprint)) throw new DevFlowError("FEATURE_CHECK_REQUIRED", "feature check is required"); state.logicComplete = true; state.lifecycle = "finalized"; state.steps.finalize = { status: "satisfied" }; }); }
