import type {
  ReviewAssurance,
  ReviewDepth,
  ReviewExecutionMode,
  ReviewFindingSeverity,
  ReviewJobCompletion,
  ReviewJobRequirement,
  ReviewRole,
  RiskLabel,
  RouteId,
} from "./types.js";

export interface ReviewSummary {
  batches: number;
  current: number;
  stale: number;
  open: number;
  complete: number;
}

export interface ReviewPointer {
  path: `review/snapshots/${string}.json`;
  sha256: string;
  revision: number;
  summary: ReviewSummary;
}

export interface ReviewBasisArtifact {
  kind: "requirements" | "implementation-plan" | "coverage-matrix" | "rollback-units";
  path: string;
  sha256: string;
}

/** All values are generated by Core and canonicalized before their hash is calculated. */
export interface ReviewBasis {
  featureId: string;
  route: RouteId;
  workflowCapabilities: Record<"trace" | "review" | "checkpoints" | "rollbackExecution", 0 | 1>;
  classification: { level: string; topology: string; execution?: string; requirements?: string; riskLabels: RiskLabel[] };
  artifacts: ReviewBasisArtifact[];
  traceability: { path: string; sha256: string; revision: number };
  projectConfigSha256: string;
  scopeManifestSha256: string;
  protectedRootsFingerprint: string;
}

export interface ReviewJob {
  jobId: string;
  role: ReviewRole;
  reviewDepth: ReviewDepth;
  packageSha256: string;
  status: "pending" | "claimed" | "submitted";
  claim?: { requestSha256: string; claimedAt: string; leaseExpiresAt: string };
  submission?: { payloadSha256: string; coverageSummary: string; findings: unknown[]; submittedAt: string };
}

export interface ReviewBatch {
  batchId: string;
  basis: ReviewBasis;
  basisHash: string;
  validity: "current" | "stale";
  progress: "open" | "complete";
  executionMode: ReviewExecutionMode;
  assuranceLevel: ReviewAssurance;
  jobs: ReviewJob[];
}

export interface ReviewLedger {
  schemaVersion: 1;
  featureId: string;
  revision: number;
  stateRevision: number;
  batches: ReviewBatch[];
  summary: ReviewSummary;
}

const reviewRoles = [
  "requirements-coverage",
  "architecture-testability",
  "rollback-operability",
  "security",
  "data-irreversibility",
] as const satisfies readonly ReviewRole[];

const reviewDepths = ["standard", "full"] as const satisfies readonly ReviewDepth[];

function protocolInvalid(message: string): never {
  throw new Error(`REVIEW_PROTOCOL_INVALID: ${message}`);
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

export function isReviewRole(value: unknown): value is ReviewRole {
  return typeof value === "string" && reviewRoles.includes(value as ReviewRole);
}

function isReviewDepth(value: unknown): value is ReviewDepth {
  return typeof value === "string" && reviewDepths.includes(value as ReviewDepth);
}

/**
 * Parse only persisted, Core-derived job requirements. Callers never choose
 * roles or depth; this parser protects future snapshot readers from drift.
 */
export function parseReviewJobRequirements(value: unknown): ReviewJobRequirement[] {
  if (!Array.isArray(value)) protocolInvalid("job requirements must be an array");
  const seen = new Set<ReviewRole>();
  return value.map((item, index) => {
    if (!isRecord(item)
      || Object.keys(item).some((key) => key !== "role" && key !== "reviewDepth")
      || !isReviewRole(item.role)
      || !isReviewDepth(item.reviewDepth)) {
      protocolInvalid(`job requirement ${index} has an invalid shape`);
    }
    if (seen.has(item.role)) protocolInvalid(`job requirement ${index} duplicates role ${item.role}`);
    seen.add(item.role);
    return { role: item.role, reviewDepth: item.reviewDepth };
  });
}

/** Validate the completion envelope without inventing a finding where none exists. */
export function parseReviewJobCompletion(value: unknown): ReviewJobCompletion {
  if (!isRecord(value)
    || Object.keys(value).some((key) => key !== "coverageSummary" && key !== "findings")
    || typeof value.coverageSummary !== "string"
    || !value.coverageSummary.trim()
    || !Array.isArray(value.findings)) {
    protocolInvalid("review job completion has an invalid shape");
  }
  return { coverageSummary: value.coverageSummary, findings: [...value.findings] };
}

/** Derive the complete 2a review assignment from immutable feature facts. */
export function deriveReviewJobRequirements(
  route: RouteId,
  riskLabels: RiskLabel[],
): ReviewJobRequirement[] {
  if (route !== "standard-m" && route !== "standard-l") return [];
  const roles: ReviewRole[] = ["requirements-coverage", "architecture-testability"];
  if (route === "standard-l") roles.push("rollback-operability");
  if (riskLabels.includes("security")) roles.push("security");
  if (riskLabels.some((label) => label === "data" || label === "money" || label === "irreversible_consequence")) {
    roles.push("data-irreversibility");
  }
  const reviewDepth: ReviewDepth = riskLabels.includes("critical_correctness") ? "full" : "standard";
  return reviewRoles
    .filter((role) => roles.includes(role))
    .map((role) => ({ role, reviewDepth }));
}

/** Executor/context strings are diagnostic only during Review 2a. */
export function assuranceForReview2a(_diagnostics?: unknown): ReviewAssurance {
  return "multi-perspective";
}
