import type {
  ReviewAssurance,
  ReviewDepth,
  ReviewExecutionMode,
  ReviewFinding,
  ReviewFindingInput,
  ReviewFindingResolutionInput,
  ReviewFindingSeverity,
  ReviewJobCompletion,
  ReviewJobRequirement,
  ReviewRole,
  RiskLabel,
  RouteId,
} from "./types.js";

export interface ReviewSummary {
  batches: number;
  current: number;
  stale: number;
  open: number;
  complete: number;
}

export interface ReviewPointer {
  path: `review/snapshots/${string}.json`;
  sha256: string;
  revision: number;
  summary: ReviewSummary;
}

export interface ReviewBasisArtifact {
  kind: "requirements" | "implementation-plan" | "coverage-matrix" | "rollback-units";
  path: string;
  sha256: string;
}

/** All values are generated by Core and canonicalized before their hash is calculated. */
export interface ReviewBasis {
  featureId: string;
  route: RouteId;
  workflowCapabilities: Record<"trace" | "review" | "checkpoints" | "rollbackExecution", 0 | 1>;
  classification: { level: string; topology: string; execution?: string; requirements?: string; riskLabels: RiskLabel[] };
  artifacts: ReviewBasisArtifact[];
  traceability: { path: string; sha256: string; revision: number };
  projectConfigSha256: string;
  scopeManifestSha256: string;
  protectedRootsFingerprint: string;
}

export interface ReviewJob {
  jobId: string;
  role: ReviewRole;
  reviewDepth: ReviewDepth;
  packageSha256: string;
  status: "pending" | "claimed" | "sampling" | "submitted";
  claim?: { requestSha256: string; claimedAt: string; leaseExpiresAt: string };
  samplingAttempts?: ReviewSamplingAttempt[];
  submission?: {
    payloadSha256: string;
    coverageSummary: string;
    findings: ReviewFinding[];
    resolutions: ReviewFindingResolutionInput[];
    submittedAt: string;
    samplingProvenance?: ReviewSamplingProvenance;
  };
}

/** Core records only request hashes; plaintext sampling IDs never enter snapshots. */
export interface ReviewSamplingAttempt {
  requestSha256: string;
  issuedAt: string;
  leaseExpiresAt: string;
  status: "issued" | "failed" | "submitted";
  completedAt?: string;
  payloadSha256?: string;
  failureCode?: "client-error" | "timeout" | "invalid-response" | "validation-failed";
}

export interface ReviewSamplingProvenance {
  requestSha256: string;
  issuedAt: string;
  completedAt: string;
}

export type ReviewFindingDisposition =
  | { kind: "resolved-in-successor"; successorBatchId: string; resolutionJobId: string; resolvedAt: string }
  | {
      kind: "risk-accepted";
      interactionId: string;
      acceptedAt: string;
      /** The exact current batch and canonical set the user accepted. */
      batchId: string;
      basisHash: string;
      findingIds: string[];
      findingSetHash: string;
    };

export interface ReviewBatch {
  batchId: string;
  basis: ReviewBasis;
  basisHash: string;
  validity: "current" | "stale";
  progress: "open" | "complete";
  executionMode: ReviewExecutionMode;
  assuranceLevel: ReviewAssurance;
  jobs: ReviewJob[];
  dispositions?: Record<string, ReviewFindingDisposition>;
}

export interface ReviewLedger {
  schemaVersion: 1;
  featureId: string;
  revision: number;
  stateRevision: number;
  batches: ReviewBatch[];
  summary: ReviewSummary;
}

/** Only persisted, successful server-issued sampling provenance can raise assurance. */
export function assuranceForReviewBatch(batch: Pick<ReviewBatch, "jobs">): ReviewAssurance {
  const sampled = batch.jobs.filter((job) => job.status === "submitted" && job.submission?.samplingProvenance);
  const hashes = new Set(sampled.map((job) => job.submission!.samplingProvenance!.requestSha256));
  return sampled.length >= 2 && hashes.size >= 2 ? "independent-sampling" : "multi-perspective";
}

const reviewRoles = [
  "requirements-coverage",
  "architecture-testability",
  "rollback-operability",
  "security",
  "data-irreversibility",
] as const satisfies readonly ReviewRole[];

const reviewDepths = ["standard", "full"] as const satisfies readonly ReviewDepth[];

function protocolInvalid(message: string): never {
  throw new Error(`REVIEW_PROTOCOL_INVALID: ${message}`);
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

export function isReviewRole(value: unknown): value is ReviewRole {
  return typeof value === "string" && reviewRoles.includes(value as ReviewRole);
}

function isReviewDepth(value: unknown): value is ReviewDepth {
  return typeof value === "string" && reviewDepths.includes(value as ReviewDepth);
}

/**
 * Parse only persisted, Core-derived job requirements. Callers never choose
 * roles or depth; this parser protects future snapshot readers from drift.
 */
export function parseReviewJobRequirements(value: unknown): ReviewJobRequirement[] {
  if (!Array.isArray(value)) protocolInvalid("job requirements must be an array");
  const seen = new Set<ReviewRole>();
  return value.map((item, index) => {
    if (!isRecord(item)
      || Object.keys(item).some((key) => key !== "role" && key !== "reviewDepth")
      || !isReviewRole(item.role)
      || !isReviewDepth(item.reviewDepth)) {
      protocolInvalid(`job requirement ${index} has an invalid shape`);
    }
    if (seen.has(item.role)) protocolInvalid(`job requirement ${index} duplicates role ${item.role}`);
    seen.add(item.role);
    return { role: item.role, reviewDepth: item.reviewDepth };
  });
}

/** Validate the completion envelope without inventing a finding where none exists. */
export function parseReviewJobCompletion(value: unknown): ReviewJobCompletion {
  if (!isRecord(value)
    || Object.keys(value).some((key) => key !== "coverageSummary" && key !== "findings" && key !== "resolutions")
    || typeof value.coverageSummary !== "string"
    || !value.coverageSummary.trim()
    || !Array.isArray(value.findings)) {
    protocolInvalid("review job completion has an invalid shape");
  }
  const findings = value.findings.map((finding, index) => parseFinding(finding, index));
  const resolutions = value.resolutions === undefined ? [] : Array.isArray(value.resolutions)
    ? value.resolutions.map((resolution, index) => parseResolution(resolution, index))
    : protocolInvalid("review job resolutions must be an array");
  return { coverageSummary: value.coverageSummary, findings, ...(resolutions.length ? { resolutions } : {}) };
}

function nonEmptyStrings(value: unknown): value is string[] {
  return Array.isArray(value) && value.length > 0 && value.every((item) => typeof item === "string" && item.trim());
}

function parseEvidence(value: unknown, label: string): Array<{ path: string; line?: number }> {
  if (!Array.isArray(value) || !value.length) protocolInvalid(`${label} evidence must be a non-empty array`);
  return value.map((item, index) => {
    const line = isRecord(item) ? item.line : undefined;
    if (!isRecord(item) || Object.keys(item).some((key) => key !== "path" && key !== "line")
      || typeof item.path !== "string" || !item.path.trim()
      || (line !== undefined && (typeof line !== "number" || !Number.isInteger(line) || line < 1))) {
      protocolInvalid(`${label} evidence ${index} has an invalid shape`);
    }
    return { path: item.path, ...(line === undefined ? {} : { line: line as number }) };
  });
}

function parseFinding(value: unknown, index: number): ReviewFindingInput {
  if (!isRecord(value) || Object.keys(value).some((key) => !["severity", "category", "targets", "evidence", "claim", "recommendation"].includes(key))
    || (value.severity !== "blocking" && value.severity !== "warning" && value.severity !== "note")
    || !isReviewRole(value.category) || !nonEmptyStrings(value.targets)
    || typeof value.claim !== "string" || !value.claim.trim() || typeof value.recommendation !== "string" || !value.recommendation.trim()) {
    protocolInvalid(`review finding ${index} has an invalid shape`);
  }
  return { severity: value.severity, category: value.category, targets: [...value.targets], evidence: parseEvidence(value.evidence, `review finding ${index}`), claim: value.claim, recommendation: value.recommendation };
}

function parseResolution(value: unknown, index: number): ReviewFindingResolutionInput {
  if (!isRecord(value) || Object.keys(value).some((key) => key !== "findingId" && key !== "evidence" && key !== "note")
    || typeof value.findingId !== "string" || !value.findingId || typeof value.note !== "string" || !value.note.trim()) {
    protocolInvalid(`review resolution ${index} has an invalid shape`);
  }
  return { findingId: value.findingId, evidence: parseEvidence(value.evidence, `review resolution ${index}`), note: value.note };
}

/** Derive the complete 2a review assignment from immutable feature facts. */
export function deriveReviewJobRequirements(
  route: RouteId,
  riskLabels: RiskLabel[],
): ReviewJobRequirement[] {
  if (route !== "standard-m" && route !== "standard-l") return [];
  const roles: ReviewRole[] = ["requirements-coverage", "architecture-testability"];
  if (route === "standard-l") roles.push("rollback-operability");
  if (riskLabels.includes("security")) roles.push("security");
  if (riskLabels.some((label) => label === "data" || label === "money" || label === "irreversible_consequence")) {
    roles.push("data-irreversibility");
  }
  const reviewDepth: ReviewDepth = riskLabels.includes("critical_correctness") ? "full" : "standard";
  return reviewRoles
    .filter((role) => roles.includes(role))
    .map((role) => ({ role, reviewDepth }));
}

/** Executor/context strings are diagnostic only during Review 2a. */
export function assuranceForReview2a(_diagnostics?: unknown): ReviewAssurance {
  return "multi-perspective";
}
