import type {
  RiskLabel,
  RouteId,
} from "./types.js";

export type ReviewAssurance =
  | "multi-perspective"
  | "independent-sampling"
  | "multi-agent-verified";

export type ReviewExecutionMode = "parallel-execution";

export type ReviewRole =
  | "code-quality"
  | "requirement-fidelity"
  | "requirements-coverage"
  | "architecture-testability"
  | "rollback-operability"
  | "security"
  | "data-irreversibility"
  | "money-safety"
  | "contract-failure"
  | "recovery-observability"
  | "critical-correctness";

/** Review 2a keeps finding categories aligned with the role that produced them. */
export type ReviewFindingCategory = ReviewRole;
export type ReviewDepth = "standard" | "full";
export type ReviewFindingSeverity = "blocking" | "warning" | "note";

export interface ReviewJobRequirement {
  role: ReviewRole;
  reviewDepth: ReviewDepth;
}

export interface ReviewJobCompletion {
  coverageSummary: string;
  findings: ReviewFindingInput[];
  resolutions?: ReviewFindingResolutionInput[];
}

export interface ReviewFindingInput {
  severity: ReviewFindingSeverity;
  category: ReviewFindingCategory;
  targets: string[];
  evidence: Array<{ path: string; line?: number }>;
  claim: string;
  recommendation: string;
}

export interface ReviewFinding extends ReviewFindingInput {
  findingId: string;
  jobId: string;
}

export interface ReviewFindingResolutionInput {
  findingId: string;
  evidence: Array<{ path: string; line?: number }>;
  note: string;
  outcome?: "resolved" | "still-blocking" | "risk-acceptance-required";
}

export interface ReviewSummary {
  batches: number;
  current: number;
  stale: number;
  open: number;
  complete: number;
}

export interface ReviewPointer {
  path: `review/snapshots/${string}.json`;
  sha256: string;
  revision: number;
  summary: ReviewSummary;
}

export interface ReviewBasisArtifact {
  kind: "requirements" | "implementation-plan";
  path: string;
  sha256: string;
}

/** All values are generated by Core and canonicalized before their hash is calculated. */
export interface ReviewBasis {
  featureId: string;
  route: RouteId;
  workflowCapabilities: Record<"trace" | "review" | "checkpoints" | "rollbackExecution", 0 | 1>;
  classification: { level: string; topology: string; requirements?: string; riskLabels: RiskLabel[] };
  artifacts: ReviewBasisArtifact[];
  traceability?: { path: string; sha256: string; revision: number };
  projectConfigSha256: string;
  /** Hashes of configured verification commands; role slices select only referenced IDs. */
  verificationCommandHashes?: Record<string, string>;
  scopeManifestSha256: string;
  governedRootsFingerprint: string;
  /** Feature-owned governed content; required for code review role basis freshness. */
  featureOwnedFingerprint?: string;
}

export interface ReviewJob {
  jobId: string;
  role: ReviewRole;
  reviewDepth: ReviewDepth;
  packageSha256: string;
  status: "pending" | "claimed" | "sampling" | "submitted" | "reused";
  roleBasisHash: string;
  reusedFrom?: { batchId: string; jobId: string; submissionSha256: string };
  claim?: { requestSha256: string; claimedAt: string; leaseExpiresAt: string };
  samplingAttempts?: ReviewSamplingAttempt[];
  carriedFindings?: Array<{
    findingId: string;
    originBatchId: string;
    originRole: ReviewRole;
    basisHash: string;
    claim: string;
    evidence: Array<{ path: string; line?: number }>;
  }>;
  submission?: {
    payloadSha256: string;
    coverageSummary: string;
    findings: ReviewFinding[];
    resolutions: ReviewFindingResolutionInput[];
    submittedAt: string;
    samplingProvenance?: ReviewSamplingProvenance;
    /** Ordinary host subagent proof; never elevates to multi-agent-verified alone. */
    attestation?: ReviewAgentAttestation;
    /** Core 派生：attestation 引用的宿主事件真实存在（调用方不能自行声明）。 */
    attestationSourceVerified?: boolean;
    /** Core 派生：隔离上下文证明（subagent 声明 + 真实宿主事件），与来源证明正交。 */
    isolationProof?: { mode: "subagent" | "sampling"; hostEventId?: string };
  };
}

export interface PublicReviewLease {
  claimedAt: string;
  leaseExpiresAt: string;
}

export type PublicReviewSamplingAttempt = Omit<ReviewSamplingAttempt, "requestSha256">;
export type PublicReviewSamplingProvenance = Omit<ReviewSamplingProvenance, "requestSha256">;
export type PublicReviewSubmission = Omit<NonNullable<ReviewJob["submission"]>, "samplingProvenance"> & {
  samplingProvenance?: PublicReviewSamplingProvenance;
};

export type PublicReviewJob = Omit<ReviewJob, "claim" | "samplingAttempts" | "submission"> & {
  lease?: PublicReviewLease;
  samplingAttempts?: PublicReviewSamplingAttempt[];
  submission?: PublicReviewSubmission;
};

/** Strip the capability hash from every client-visible review projection. */
export function toPublicReviewJob(job: ReviewJob): PublicReviewJob {
  const { claim, samplingAttempts, submission, ...publicJob } = job;
  return {
    ...publicJob,
    ...(claim ? { lease: { claimedAt: claim.claimedAt, leaseExpiresAt: claim.leaseExpiresAt } } : {}),
    ...(samplingAttempts ? {
      samplingAttempts: samplingAttempts.map(({ requestSha256: _requestSha256, ...attempt }) => attempt),
    } : {}),
    ...(submission ? {
      submission: {
        ...submission,
        ...(submission.samplingProvenance ? {
          samplingProvenance: {
            issuedAt: submission.samplingProvenance.issuedAt,
            completedAt: submission.samplingProvenance.completedAt,
          },
        } : {}),
      },
    } : {}),
  };
}

/** Core records only request hashes; plaintext sampling IDs never enter snapshots. */
export interface ReviewSamplingAttempt {
  requestSha256: string;
  issuedAt: string;
  leaseExpiresAt: string;
  status: "issued" | "failed" | "submitted";
  completedAt?: string;
  payloadSha256?: string;
  failureCode?: "client-error" | "timeout" | "invalid-response" | "validation-failed";
}

export interface ReviewSamplingProvenance {
  requestSha256: string;
  issuedAt: string;
  completedAt: string;
}

/** Persisted host subagent proof. Callers cannot write assuranceLevel or verified. */
export interface ReviewAgentAttestation {
  host: "claude" | "codex";
  agentId: string;
  issuedAt: string;
  raw: string;
  rawSha256: string;
  acceptedAt: string;
  /** 调用方声明的宿主可信事件；只有 Core 校验存在后才计入来源证明。 */
  hostEventId?: string;
  /** 声明该审查在与实施隔离的新上下文中完成（如宿主 subagent）；Core 校验事件后才形成隔离证明。 */
  isolated?: boolean;
}

/** Future trusted hosts plug in here; the default verifier never attests verified. */
export interface ReviewIdentityVerifier {
  verify(attestation: ReviewAgentAttestation): { trusted: boolean };
}

export const defaultReviewIdentityVerifier: ReviewIdentityVerifier = {
  verify: () => ({ trusted: false }),
};

export type ReviewEvidenceSource = "role-jobs" | "server-sampling" | "host-attestation";

export type ReviewFindingDisposition =
  | { kind: "resolved-in-successor"; successorBatchId: string; resolutionJobId: string; resolvedAt: string }
  | {
      kind: "risk-accepted";
      interactionId: string;
      acceptedAt: string;
      /** The exact current batch and canonical set the user accepted. */
      batchId: string;
      basisHash: string;
      findingIds: string[];
      findingSetHash: string;
    };

export type ReviewFindingEvent =
  | {
      type: "origin";
      finding: ReviewFinding;
      batchId: string;
      role: ReviewRole;
      basisHash: string;
      at: string;
    }
  | {
      type: "resolved";
      findingId: string;
      successorBatchId: string;
      resolutionJobId: string;
      basisHash: string;
      evidence: ReviewFindingResolutionInput;
      at: string;
    }
  | {
      type: "still-blocking";
      findingId: string;
      successorBatchId: string;
      resolutionJobId: string;
      basisHash: string;
      reason: string;
      at: string;
    }
  | {
      type: "risk-accepted";
      findingId: string;
      batchId: string;
      interactionId: string;
      basisHash: string;
      findingSetHash: string;
      userEvidence: string;
      at: string;
    };

export interface ReviewBatch {
  batchId: string;
  /** v6 contract: every batch declares its review phase (GPT-005). */
  phase: "plan" | "code";
  basis: ReviewBasis;
  basisHash: string;
  validity: "current" | "stale";
  progress: "open" | "complete";
  executionMode: ReviewExecutionMode;
  assuranceLevel: ReviewAssurance;
  jobs: ReviewJob[];
  dispositions?: Record<string, ReviewFindingDisposition>;
  /** 未知 diff 全量重审的诊断：变化字段、未命中切片的原因与重审决定。 */
  unknownDiffInfo?: { changedFields: string[]; reason: string };
}

export interface ReviewLedger {
  schemaVersion: 3;
  featureId: string;
  revision: number;
  stateRevision: number;
  batches: ReviewBatch[];
  summary: ReviewSummary;
  /** v3 append-only finding history; old batch dispositions are never authoritative. */
  findingEvents?: ReviewFindingEvent[];
}

/**
 * Derive assurance only from persisted Core evidence.
 * Ladder: multi-agent-verified (trusted verifier only) >
 * independent-sampling (≥2 jobs, distinct sampling request hashes) >
 * multi-perspective.
 * Free-text attestation, display names, agentIds or raw hashes cannot prove
 * distinct sources by themselves (ADR-0007 / issue 18).
 */
export function assuranceForReviewBatch(
  batch: Pick<ReviewBatch, "jobs">,
  verifier: ReviewIdentityVerifier = defaultReviewIdentityVerifier,
): ReviewAssurance {
  const attested = batch.jobs.filter((job) => job.status === "submitted" && job.submission?.attestation);
  const trusted = attested.filter((job) => verifier.verify(job.submission!.attestation!).trusted);
  const trustedAgents = new Set(trusted.map((job) => job.submission!.attestation!.agentId));
  const trustedRaws = new Set(trusted.map((job) => job.submission!.attestation!.rawSha256));
  if (trusted.length >= 2 && trustedAgents.size >= 2 && trustedRaws.size >= 2) return "multi-agent-verified";

  const sampled = batch.jobs.filter((job) => job.status === "submitted" && job.submission?.samplingProvenance);
  const hashes = new Set(sampled.map((job) => job.submission!.samplingProvenance!.requestSha256));
  if (sampled.length >= 2 && hashes.size >= 2) return "independent-sampling";
  return "multi-perspective";
}

/** Honest projection labels for which evidence classes contributed. */
export function evidenceSourcesForReviewBatch(batch: Pick<ReviewBatch, "jobs"> | undefined): ReviewEvidenceSource[] {
  if (!batch) return [];
  const sources: ReviewEvidenceSource[] = [];
  if (batch.jobs.some((job) => job.status === "submitted")) sources.push("role-jobs");
  if (batch.jobs.some((job) => job.submission?.samplingProvenance)) sources.push("server-sampling");
  if (batch.jobs.some((job) => job.submission?.attestation)) sources.push("host-attestation");
  return sources;
}

/** Parse host attestation input. Rejects verified/assurance self-reports. */
export function parseHostAttestation(value: unknown): Omit<ReviewAgentAttestation, "rawSha256" | "acceptedAt"> {
  if (!isRecord(value)
    || Object.keys(value).some((key) => !["host", "agentId", "issuedAt", "raw", "hostEventId", "isolated"].includes(key))
    || (value.host !== "claude" && value.host !== "codex")
    || typeof value.agentId !== "string" || !value.agentId.trim()
    || typeof value.issuedAt !== "string" || !value.issuedAt.trim()
    || Number.isNaN(Date.parse(value.issuedAt))
    || typeof value.raw !== "string" || !value.raw.trim()) {
    protocolInvalid("host attestation has an invalid shape");
  }
  return {
    host: value.host,
    agentId: value.agentId.trim(),
    issuedAt: value.issuedAt,
    raw: value.raw,
    ...(typeof value.hostEventId === "string" && value.hostEventId.trim() ? { hostEventId: value.hostEventId.trim() } : {}),
    ...(value.isolated === true ? { isolated: true } : {}),
  };
}

const reviewRoles = [
  "code-quality",
  "requirement-fidelity",
  "requirements-coverage",
  "architecture-testability",
  "rollback-operability",
  "security",
  "data-irreversibility",
  "money-safety",
  "contract-failure",
  "recovery-observability",
  "critical-correctness",
] as const satisfies readonly ReviewRole[];

const reviewDepths = ["standard", "full"] as const satisfies readonly ReviewDepth[];

function protocolInvalid(message: string): never {
  throw new Error(`REVIEW_PROTOCOL_INVALID: ${message}`);
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

export function isReviewRole(value: unknown): value is ReviewRole {
  return typeof value === "string" && reviewRoles.includes(value as ReviewRole);
}

function isReviewDepth(value: unknown): value is ReviewDepth {
  return typeof value === "string" && reviewDepths.includes(value as ReviewDepth);
}

/**
 * Parse only persisted, Core-derived job requirements. Callers never choose
 * roles or depth; this parser protects future snapshot readers from drift.
 */
export function parseReviewJobRequirements(value: unknown): ReviewJobRequirement[] {
  if (!Array.isArray(value)) protocolInvalid("job requirements must be an array");
  const seen = new Set<ReviewRole>();
  return value.map((item, index) => {
    if (!isRecord(item)
      || Object.keys(item).some((key) => key !== "role" && key !== "reviewDepth")
      || !isReviewRole(item.role)
      || !isReviewDepth(item.reviewDepth)) {
      protocolInvalid(`job requirement ${index} has an invalid shape`);
    }
    if (seen.has(item.role)) protocolInvalid(`job requirement ${index} duplicates role ${item.role}`);
    seen.add(item.role);
    return { role: item.role, reviewDepth: item.reviewDepth };
  });
}

/** Validate the completion envelope without inventing a finding where none exists. */
export function parseReviewJobCompletion(value: unknown): ReviewJobCompletion {
  if (!isRecord(value)
    || Object.keys(value).some((key) => key !== "coverageSummary" && key !== "findings" && key !== "resolutions")
    || typeof value.coverageSummary !== "string"
    || !value.coverageSummary.trim()
    || !Array.isArray(value.findings)) {
    protocolInvalid("review job completion has an invalid shape");
  }
  const findings = value.findings.map((finding, index) => parseFinding(finding, index));
  const resolutions = value.resolutions === undefined ? [] : Array.isArray(value.resolutions)
    ? value.resolutions.map((resolution, index) => parseResolution(resolution, index))
    : protocolInvalid("review job resolutions must be an array");
  return { coverageSummary: value.coverageSummary, findings, ...(resolutions.length ? { resolutions } : {}) };
}

function nonEmptyStrings(value: unknown): value is string[] {
  return Array.isArray(value) && value.length > 0 && value.every((item) => typeof item === "string" && item.trim());
}

function parseEvidence(value: unknown, label: string): Array<{ path: string; line?: number }> {
  if (!Array.isArray(value) || !value.length) protocolInvalid(`${label} evidence must be a non-empty array`);
  return value.map((item, index) => {
    const line = isRecord(item) ? item.line : undefined;
    if (!isRecord(item) || Object.keys(item).some((key) => key !== "path" && key !== "line")
      || typeof item.path !== "string" || !item.path.trim()
      || (line !== undefined && (typeof line !== "number" || !Number.isInteger(line) || line < 1))) {
      protocolInvalid(`${label} evidence ${index} has an invalid shape`);
    }
    return { path: item.path, ...(line === undefined ? {} : { line: line as number }) };
  });
}

function parseFinding(value: unknown, index: number): ReviewFindingInput {
  if (!isRecord(value) || Object.keys(value).some((key) => !["severity", "category", "targets", "evidence", "claim", "recommendation"].includes(key))
    || (value.severity !== "blocking" && value.severity !== "warning" && value.severity !== "note")
    || !isReviewRole(value.category) || !nonEmptyStrings(value.targets)
    || typeof value.claim !== "string" || !value.claim.trim() || typeof value.recommendation !== "string" || !value.recommendation.trim()) {
    protocolInvalid(`review finding ${index} has an invalid shape`);
  }
  return { severity: value.severity, category: value.category, targets: [...value.targets], evidence: parseEvidence(value.evidence, `review finding ${index}`), claim: value.claim, recommendation: value.recommendation };
}

function parseResolution(value: unknown, index: number): ReviewFindingResolutionInput {
  if (!isRecord(value) || Object.keys(value).some((key) => key !== "findingId" && key !== "evidence" && key !== "note" && key !== "outcome")
    || typeof value.findingId !== "string" || !value.findingId || typeof value.note !== "string" || !value.note.trim()) {
    protocolInvalid(`review resolution ${index} has an invalid shape`);
  }
  if (value.outcome !== undefined && value.outcome !== "resolved" && value.outcome !== "still-blocking" && value.outcome !== "risk-acceptance-required") protocolInvalid(`review resolution ${index} has an invalid outcome`);
  return { findingId: value.findingId, evidence: parseEvidence(value.evidence, `review resolution ${index}`), note: value.note, ...(value.outcome ? { outcome: value.outcome } : {}) };
}

/** Derive the complete 2a review assignment from immutable feature facts. */
export function deriveReviewJobRequirements(
  route: RouteId,
  riskLabels: RiskLabel[],
  derivedRoles?: ReviewRole[],
  phase: "plan" | "code" = "plan",
): ReviewJobRequirement[] {
  if (phase === "code") {
    const reviewDepth: ReviewDepth = riskLabels.includes("critical_correctness") ? "full" : "standard";
    return ["code-quality", "requirement-fidelity"].map((role) => ({ role: role as ReviewRole, reviewDepth }));
  }
  if (route !== "m" && route !== "l") return [];
  const roles: ReviewRole[] = derivedRoles?.length ? [...derivedRoles] : ["requirements-coverage", "architecture-testability", "rollback-operability"];
  if (!derivedRoles && riskLabels.includes("security")) roles.push("security");
  if (!derivedRoles && riskLabels.some((label) => label === "data" || label === "money" || label === "irreversible_consequence")) {
    roles.push("data-irreversibility");
  }
  const reviewDepth: ReviewDepth = riskLabels.includes("critical_correctness") ? "full" : "standard";
  return reviewRoles
    .filter((role) => roles.includes(role))
    .map((role) => ({ role, reviewDepth }));
}

/** Executor/context strings are diagnostic only during Review 2a. */
export function assuranceForReview2a(_diagnostics?: unknown): ReviewAssurance {
  return "multi-perspective";
}
